name: Task CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run Test
        run: |
          npm install
          npm run test

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/task-api:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/task-api:latest

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env: 
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
           curl "$deploy_url"
