name: Say Hello

on: 
  push:  # Trigger on any push
    branches:
      - main  # Only run when pushing to main branch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
