name: Task CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/task-api:latest .

      - name: Run tests in container
        run: docker run ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }} npm test

      - name: Push Docker images
        if: github.ref == 'refs/heads/main' && success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/task-api:latest

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main' && success()
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "image": "${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }}",
              "envVars": {
                "NODE_ENV": "production",
                "PORT": "3000",
                "DB_USERNAME": "${{ secrets.DB_USERNAME }}",
                "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}"
              }
            }' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
