name: Task CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --no-cache \
            -t ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }} .

      - name: Run tests in container
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }} npm test

      - name: Push Docker image for this commit
        if: github.ref == 'refs/heads/main' && success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task-api:${{ github.sha }}

      - name: Deploy to Render with commit-specific image
        if: github.ref == 'refs/heads/main' && success()
        env: 
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
           curl "$deploy_url"
